/* Generated by           cobc 2.2.0 */
/* Generated from         /Volumes/DeVere/kristofer/Documents/Projects/cobol-lab1-kristofer/hello.cbl */
/* Generated at           May 01 2020 11:16:55 */
/* GnuCOBOL build date    Oct 15 2019 14:14:21 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -x -g -d -j -std=ibm -fdebugging-line -fsource-location -ftraceall /Volumes/DeVere/kristofer/Documents/Projects/cobol-lab1-kristofer/hello.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"/Volumes/DeVere/kristofer/Documents/Projects/cobol-lab1-kristofer/hello.cbl"
#define  COB_PACKAGE_VERSION		"2.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"May 01 2020 11:16:55"
#define  COB_MODULE_DATE		20200501
#define  COB_MODULE_TIME		111655

/* Global variables */
#include "hello.c.h"

/* Function prototypes */

static int		HELLO__WORLD ();
static int		HELLO__WORLD_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (HELLO__WORLD ());
}

/* Functions */

/* PROGRAM-ID 'HELLO-WORLD' */

/* ENTRY 'HELLO__WORLD' */

static int
HELLO__WORLD ()
{
  return HELLO__WORLD_ (0);
}

static int
HELLO__WORLD_ (const int entry)
{
  /* Program local variables */
  #include "hello.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 5         : Entry     HELLO-WORLD             : /Volumes/DeVere/kristofer/Documents/Projects/cobol-lab1-kristofer/hello.cbl */
  l_2:;
  cob_trace_section (st_1, st_2, 5);
  cob_trace_section (st_3, st_2, 5);
  cob_trace_section (st_4, st_2, 5);

  /* Line: 5         : DISPLAY            : /Volumes/DeVere/kristofer/Documents/Projects/cobol-lab1-kristofer/hello.cbl */
  cob_set_location (st_2, 5, NULL, NULL, st_5);
  cob_display (0, 1, 1, &c_1);

  /* Line: 6         : STOP RUN           : /Volumes/DeVere/kristofer/Documents/Projects/cobol-lab1-kristofer/hello.cbl */
  cob_set_location (st_2, 6, NULL, NULL, st_6);
  cob_stop_run (b_2);

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_section (st_7, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;

  /* Frame stack jump table */
  P_switch:
   cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize module structure */
  module->module_name = "HELLO-WORLD";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())HELLO__WORLD;
  module->module_cancel.funcptr = (void *(*)())HELLO__WORLD_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 0;
  module->flag_pretty_display = 0;
  module->flag_host_sign = 1;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  initialized = 0;

  P_clear_decimal:

  return 0;

}

/* End PROGRAM-ID 'HELLO-WORLD' */

/* End functions */

