/* Generated by           cobc 2.2.0 */
/* Generated from         /Volumes/DeVere/kristofer/Documents/Projects/cobol-lab1-kristofer/sayname.cbl */
/* Generated at           May 01 2020 11:26:15 */
/* GnuCOBOL build date    Oct 15 2019 14:14:21 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -x -g -d -j -std=ibm -fdebugging-line -fsource-location -ftraceall /Volumes/DeVere/kristofer/Documents/Projects/cobol-lab1-kristofer/sayname.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {19, (cob_u8_ptr)"What is your name\? ", &a_1};
static const cob_field c_2	= {6, (cob_u8_ptr)"Hello ", &a_1};


/* Strings */
static const char st_1[]	= "Entry:     HELLO-WORLD";
static const char st_2[]	= "/Volumes/DeVere/kristofer/Documents/Projects/cobol-lab1-kristofer/sayname.cbl";
static const char st_3[]	= "Section:   (None)";
static const char st_4[]	= "Paragraph: (None)";
static const char st_5[]	= "DISPLAY";
static const char st_6[]	= "ACCEPT";
static const char st_7[]	= "STOP RUN";
static const char st_8[]	= "Exit:      HELLO-WORLD";

	/* Decimal constants */
