/* Generated by           cobc 2.2.0 */
/* Generated from         /Volumes/DeVere/kristofer/Documents/Projects/cobol-lab1-kristofer/sayname.cbl */
/* Generated at           May 01 2020 11:26:15 */
/* GnuCOBOL build date    Oct 15 2019 14:14:21 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -x -g -d -j -std=ibm -fdebugging-line -fsource-location -ftraceall /Volumes/DeVere/kristofer/Documents/Projects/cobol-lab1-kristofer/sayname.cbl */

/* Program local variables for 'HELLO-WORLD' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*temp_index;
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_6[8] __attribute__((aligned));	/* NAME */

/* End of data storage */


/* Fields */
static cob_field f_6	= {8, b_6, &a_2};	/* NAME */

/* End of fields */

